# Load data

In [2]:
import polars as pl

train_df = pl.read_csv("data/from_host/train.csv")
train_df.describe()

shape: (9, 15)
┌────────────┬────────────┬───────────┬──────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ statistic  ┆ StudyInsta ┆ Report    ┆ ACL      ┆ … ┆ Synovitis ┆ Baker's  ┆ Contusion ┆ Fracture │
│ ---        ┆ nceUID     ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---      ┆ ---       ┆ ---      │
│ str        ┆ ---        ┆ str       ┆ f64      ┆   ┆ f64       ┆ f64      ┆ f64       ┆ f64      │
│            ┆ str        ┆           ┆          ┆   ┆           ┆          ┆           ┆          │
╞════════════╪════════════╪═══════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ count      ┆ 4407       ┆ 4407      ┆ 58.0     ┆ … ┆ 58.0      ┆ 58.0     ┆ 58.0      ┆ 58.0     │
│ null_count ┆ 0          ┆ 0         ┆ 4349.0   ┆ … ┆ 4349.0    ┆ 4349.0   ┆ 4349.0    ┆ 4349.0   │
│ mean       ┆ null       ┆ null      ┆ 0.413793 ┆ … ┆ 0.465517  ┆ 0.206897 ┆ 0.327586  ┆ 0.310345 │
│ std        ┆ null       ┆ null      ┆ 0.496814 ┆ … ┆ 0.503166  ┆ 0.408619 ┆ 0.473432  ┆ 0.466675 │
│ min        ┆ 1.2.826.0. ┆ The study ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0      ┆ 0.0       ┆ 0.0      │
│            ┆ 1.3680043. ┆ reveals   ┆          ┆   ┆           ┆          ┆           ┆          │
│            ┆ 8.498.1000 ┆ norm…     ┆          ┆   ┆           ┆          ┆           ┆          │
│            ┆ …          ┆           ┆          ┆   ┆           ┆          ┆           ┆          │
│ 25%        ┆ null       ┆ null      ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0      ┆ 0.0       ┆ 0.0      │
│ 50%        ┆ null       ┆ null      ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0      ┆ 0.0       ┆ 0.0      │
│ 75%        ┆ null       ┆ null      ┆ 1.0      ┆ … ┆ 1.0       ┆ 0.0      ┆ 1.0       ┆ 1.0      │
│ max        ┆ 1.2.826.0. ┆ ∆ΕΞΙΟ     ┆ 1.0      ┆ … ┆ 1.0       ┆ 1.0      ┆ 1.0       ┆ 1.0      │
│            ┆ 1.3680043. ┆ ΓΟΝΑΤΟ    ┆          ┆   ┆           ┆          ┆           ┆          │
│            ┆ 8.498.9995 ┆ Τεχνική Η ┆          ┆   ┆           ┆          ┆           ┆          │
│            ┆ …          ┆ εξέταση…  ┆          ┆   ┆           ┆          ┆           ┆          │
└────────────┴────────────┴───────────┴──────────┴───┴───────────┴──────────┴───────────┴──────────┘

In [3]:
train_df.head()

shape: (5, 14)
┌─────────────────┬─────────────────┬──────┬──────┬───┬───────────┬─────────┬───────────┬──────────┐
│ StudyInstanceUI ┆ Report          ┆ ACL  ┆ MCL  ┆ … ┆ Synovitis ┆ Baker's ┆ Contusion ┆ Fracture │
│ D               ┆ ---             ┆ ---  ┆ ---  ┆   ┆ ---       ┆ ---     ┆ ---       ┆ ---      │
│ ---             ┆ str             ┆ i64  ┆ i64  ┆   ┆ i64       ┆ i64     ┆ i64       ┆ i64      │
│ str             ┆                 ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
╞═════════════════╪═════════════════╪══════╪══════╪═══╪═══════════╪═════════╪═══════════╪══════════╡
│ 1.2.826.0.1.368 ┆ Técnica: RMN de ┆ null ┆ null ┆ … ┆ null      ┆ null    ┆ null      ┆ null     │
│ 0043.8.498.1000 ┆ la rodilla. Re… ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│ …               ┆                 ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│ 1.2.826.0.1.368 ┆ [DATE]: * MR    ┆ null ┆ null ┆ … ┆ null      ┆ null    ┆ null      ┆ null     │
│ 0043.8.498.1000 ┆ Knie Rechts     ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│ …               ┆ 15ch …          ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│ 1.2.826.0.1.368 ┆ Hallazgos:      ┆ null ┆ null ┆ … ┆ null      ┆ null    ┆ null      ┆ null     │
│ 0043.8.498.1000 ┆ No hay          ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│ …               ┆ alteraciones…   ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│ 1.2.826.0.1.368 ┆ In the medial   ┆ null ┆ null ┆ … ┆ null      ┆ null    ┆ null      ┆ null     │
│ 0043.8.498.1000 ┆ compartment,    ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│ …               ┆ th…             ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│ 1.2.826.0.1.368 ┆ CONSTATATIONS : ┆ null ┆ null ┆ … ┆ null      ┆ null    ┆ null      ┆ null     │
│ 0043.8.498.1001 ┆                 ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│ …               ┆ Fractures :     ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
│                 ┆ A…              ┆      ┆      ┆   ┆           ┆         ┆           ┆          │
└─────────────────┴─────────────────┴──────┴──────┴───┴───────────┴─────────┴───────────┴──────────┘